### ISSUE TITLE
make test does not work on windows

### ISSUE THREAD

**Issue by el-j** [fritzing/fzz-js#1]
```
[path]\fzz-js [master ≡ +1 ~1 -0 !]> make test
Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
make: *** [test] Fehler 1
[path]\fzz-js [master ≡ +1 ~0 -0 !]>
```

der fehler liegt im makefile 1. zeile: 
`BIN = ./node_modules/.bin`

./ ist keine gültige Angabe auf win-systemen

schreibt man die pfade um läuft der test durch
```
BIN = node_modules\.bin


all: lint test
lint:
	@$(BIN)\eslint .
lint-fix:
	@$(BIN)\eslint . --fix
test:
	@$(BIN)\jest
.PHONY: all lint lint-fix test

docs:
	@$(BIN)\esdoc
docs-open: docs
	@open docs\index.html
.PHONY: docs docs-open

```

**Comment by paulvollmer** [comment]
ok, das ist natürlich schlecht. die makefile unter anderem dafür da die tests, das linting auf travis zu starten... wir müssen mal schauen wie man da windows support einbringen kann.

du kannst ja erstmal deine lokal gefixte version nutzen
